#!/bin/sh

echo 'Starting Redis server.'
echo '/usr/local/bin/redis-server conf/redis.conf &'
/usr/local/bin/redis-server conf/redis.conf &
echo $! > conf/redis.pid

echo 'Starting Alias web server.'
echo 'alias.py &'
./alias.py &
echo $! > conf/alias.pid
