#!/bin/sh

echo 'Starting Redis server.'
echo '/usr/local/bin/redis-server conf/redis.conf &'
/usr/local/bin/redis-server conf/redis.conf &
echo $! > conf/redis.pid

echo 'Starting Alias web server.'
echo 'alias_server &'
/usr/bin/env python alias_server &
echo $! > conf/alias.pid
